### ISSUE TITLE
8189fs module floods terminal

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [geomatsi/meta-sunxi-contrib#3]
Hi,
I'm using the 8189fs module on my pc-plus and it works find under warrior. Mostly. The terminal is being flooded with status massages (which should actually go to syslog). E.g. after connecting the power (I think) is reported (very often):

    [  786.580996] RTL871X: CurIGValue=48, EntryMinUndecoratedSmoothedPWDB = 51

Did you see this behavior before? Do you know if the verbosity can be changed?
We will be using the later on in headless mode thus in everyday usage it's not going to be that much of a problem but for developing this is quite annoying.

Best regards

**Comment by HerrMuellerluedenscheid** [comment]
Probably worth noting: I upgraded the 8189fs module which is being pulled to the latest commit of the used branch, which is `86dba26`

**Comment by HerrMuellerluedenscheid** [comment]
No, actually, I did not do that. I mixed things up between two machines that I use to build. Let me check with the latest version of the driver as this seems to apply a couple of fixes respecting the kernel version 4.19.

**Comment by geomatsi** [comment]
Yes, I am aware of that verbosity issue. IIRC there is a module configuration option that can be used to tweak verbosity. You may take a look at README and Makefile in 8189fs repo and look for that option. Recipe modification should be straightforward.

**Comment by HerrMuellerluedenscheid** [comment]
Thanks! I think I found the place where the debug levels are defined https://github.com/jwrdegoede/rtl8189ES_linux/blob/rtl8189fs/hal/phydm/phydm_debug.h

I haven't figured out how to set the level though. But once I get to it, I'll leave a comment here.

**Comment by geomatsi** [comment]
Hi @HerrMuellerluedenscheid 
I guess you can make a patch for that string and put that patch into recipes-bsp/rtl8189fs-mod/rtl8189fs-mod

**Comment by HerrMuellerluedenscheid** [comment]
Hey,
Thanks, sure. I just don't find the global entry point that sets the verbosity at runtime.
Anyway, I'll figure out how to do that the sooner or later.
Regards
